openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    user_registration:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
        password_confirmation:
          type: string
    user_login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
tags:
- name: Users
- name: Authentication
- name: Search
paths:
  "/api/v1/auth/signup":
    post:
      tags:
      - Authentication
      summary: Creates a new user
      parameters: []
      responses:
        '200':
          description: User created
        '401':
          description: User already exists
        '422':
          description: Invalid request
        '500':
          description: Internal server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  "$ref": "#/components/schemas/user_registration"
        required: true
  "/api/v1/auth/login":
    post:
      tags:
      - Authentication
      summary: Logs in a user
      parameters: []
      responses:
        '200':
          description: User created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  "$ref": "#/components/schemas/user_login"
        required: true
  "/api/v1/auth/logout":
    delete:
      tags:
      - Authentication
      security:
      - bearer_auth: []
      summary: Logs out current logged-in user
      description: ''
      operationId: logout
      parameters: []
      responses:
        default:
          description: Success
  "/api/v1/auth/me":
    get:
      tags:
      - Users
      security:
      - bearer_auth: []
      summary: Returns current logged-in user
      description: ''
      operationId: me
      parameters: []
      responses:
        default:
          description: Success
  "/api/v1/users/show/{username}":
    get:
      tags:
      - Users
      security:
      - bearer_auth: []
      summary: Returns user by username
      description: ''
      operationId: getUser
      parameters:
      - name: username
        in: path
        description: Username of user
        required: true
        schema:
          type: string
      responses:
        default:
          description: Success
  "/api/v1/search":
    get:
      tags:
      - Search
      security:
      - bearer_auth: []
      summary: Searches for a user by username
      description: ''
      operationId: searchUser
      parameters:
      - in: query
        name: username
        description: Username to search for
        required: true
        schema:
          type: string
      responses:
        default:
          description: Success
  "/api/v1/organizations/{organization_id}/users/{user_id}/assistances":
    post:
      tags:
      - Organizations
      - Users
      - Assistances
      security:
      - bearer_auth: []
      summary: Creates an assistance for a user within an organization
      operationId: createAssistance
      parameters:
      - name: organization_id
        in: path
        description: ID of the organization
        required: true
        schema:
          type: string
      - name: user_id
        in: path
        description: ID of the user
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                assistance:
                  type: object
                  # Add properties for assistance
        required: true
      responses:
        '201':
          description: Assistance created
        '401':
          description: Unauthorized
        '422':
          description: Invalid request
        '500':
          description: Internal server error
  "/api/v1/organizations/{organization_id}/users/{user_id}/assistances":
    get:
      tags:
      - Organizations
      - Users
      - Assistances
      security:
      - bearer_auth: []
      summary: Lists all assistances for a user within an organization
      operationId: listAssistances
      parameters:
      - name: organization_id
        in: path
        description: ID of the organization
        required: true
        schema:
          type: string
      - name: user_id
        in: path
        description: ID of the user
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
  "/api/v1/organizations/{organization_id}/departments/{department_id}/positions":
    get:
      tags:
      - Organizations
      - Departments
      - Positions
      security:
      - bearer_auth: []
      summary: Lists all positions within a department of an organization
      operationId: listPositions
      parameters:
      - name: organization_id
        in: path
        description: ID of the organization
        required: true
        schema:
          type: string
      - name: department_id
        in: path
        description: ID of the department
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
  "/api/v1/organizations/{organization_id}/salaries/user_salaries":
    get:
      tags:
      - Organizations
      - Salaries
      security:
      - bearer_auth: []
      summary: Lists salaries for all users within an organization
      operationId: listUserSalaries
      parameters:
      - name: organization_id
        in: path
        description: ID of the organization
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
  "/api/v1/organizations/{organization_id}/reports/{user_id}/journeys":
    get:
      tags:
      - Organizations
      - Reports
      security:
      - bearer_auth: []
      summary: Retrieves journey report for a user within an organization
      operationId: getJourneyReport
      parameters:
      - name: organization_id
        in: path
        description: ID of the organization
        required: true
        schema:
          type: string
      - name: user_id
        in: path
        description: ID of the user
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
servers:
- url: http://{localhost}
  variables:
    localhost:
      default: localhost:3000
